package com.model.pojo;
// Generated Sep 28, 2024 1:16:40 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProjectWorker generated by hbm2java
 */
@Entity
@Table(name="project_worker"
    ,catalog="flow_manage"
)
public class ProjectWorker  implements java.io.Serializable {


     private ProjectWorkerId id;
     private Project project;
     private User user;
     private String role;

    public ProjectWorker() {
    }

    public ProjectWorker(ProjectWorkerId id, Project project, User user, String role) {
       this.id = id;
       this.project = project;
       this.user = user;
       this.role = role;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ), 
        @AttributeOverride(name="projectId", column=@Column(name="project_id", nullable=false) ) } )
    public ProjectWorkerId getId() {
        return this.id;
    }
    
    public void setId(ProjectWorkerId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity = Project.class)
    @JoinColumn(name="project_id", nullable=false, insertable=false, updatable=false)
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

@ManyToOne(fetch=FetchType.LAZY, targetEntity = User.class)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="role", nullable=false, length=20)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


