package com.model.pojo;
// Generated Sep 28, 2024 1:16:40 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name="task"
    ,catalog="flow_manage"
)
public class Task  implements java.io.Serializable {


     private int id;
     private Project project;
     private Status status;
     private User user;
     private String title;
     private int priority;
     private Date deadline;
     private String description;

    public Task() {
    }

    public Task(int id, Project project, Status status, User user, String title, String description, int priority, Date deadline) {
       this.id = id;
       this.project = project;
       this.status = status;
       this.user = user;
       this.title = title;
       this.description = description;
       this.priority = priority;
       this.deadline = deadline;
    }
    
    public Task(Project project, Status status, User user, String title, String description, int priority, Date deadline) {
       this.project = project;
       this.status = status;
       this.user = user;
       this.title = title;
       this.description = description;
       this.priority = priority;
       this.deadline = deadline;
    }
   
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity = Project.class)
    @JoinColumn(name="project_id", nullable=false)
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity = Status.class)
    @JoinColumn(name="status_id", nullable=false)
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

    @ManyToOne(fetch=FetchType.LAZY, targetEntity = User.class)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="description", nullable=true, length=65535)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="priority", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="deadline", nullable=false, length=10)
    public Date getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }




}


